version: "3.9"

services: 
  app:
    build: .
    volumes:
      - .:/django
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:80
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgress_db