# Generated by Django 4.2.11 on 2024-04-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_release_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='description',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
