# Generated by Django 4.2.11 on 2024-04-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_release_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
