# Generated by Django 4.2.11 on 2024-04-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_artist_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='release',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
