# Generated by Django 4.2.11 on 2024-04-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_genre_picture_release_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-date']},
        ),
    ]
