# Generated by Django 4.2.11 on 2024-04-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_alter_release_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
